name: communicator
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.3.8
  sqflite:
  sqflite_common_ffi: any
  path:
  provider: ^6.1.2
  positioned_scroll_observer: ^2.2.2
  http: ^1.2.0
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/databases/initial_structures.sql
    - backend/
